/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package _06_Interfaces;

import _02_EDD.UndirectedGraph;

/**
 *
 * @author blanf
 */
public class Menu extends javax.swing.JFrame {

    UndirectedGraph GraphOfProgram;
    
    /**
     * Creates new form Ventana2
     */
    public Menu() {
        this.GraphOfProgram=new UndirectedGraph();
        initComponents();                       
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public Menu(UndirectedGraph GraphToProgram) {
        this.GraphOfProgram= GraphToProgram;
        initComponents();                       
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ModifyGraph = new javax.swing.JButton();
        LoadGraph = new javax.swing.JButton();
        NewSimulation = new javax.swing.JButton();
        ShowGraph = new javax.swing.JButton();
        SaveGraphInTXT = new javax.swing.JButton();
        CloseProgram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú");

        ModifyGraph.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ModifyGraph.setText("Modificar grafo");
        ModifyGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyGraphActionPerformed(evt);
            }
        });

        LoadGraph.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadGraph.setText("Cargar grafo");
        LoadGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGraphActionPerformed(evt);
            }
        });

        NewSimulation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewSimulation.setText("Nueva simulación");
        NewSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSimulationActionPerformed(evt);
            }
        });

        ShowGraph.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ShowGraph.setText("Mostrar grafo");
        ShowGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowGraphActionPerformed(evt);
            }
        });

        SaveGraphInTXT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SaveGraphInTXT.setText("Guardar grafo");
        SaveGraphInTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveGraphInTXTActionPerformed(evt);
            }
        });

        CloseProgram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CloseProgram.setText("Finalizar");
        CloseProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LoadGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ShowGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SaveGraphInTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ModifyGraph, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CloseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewSimulation)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(NewSimulation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoadGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveGraphInTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(CloseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifyGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyGraphActionPerformed
    Modify a = new Modify();
    a.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_ModifyGraphActionPerformed

    private void LoadGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGraphActionPerformed
    Load loadWindow = new Load();
    loadWindow.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_LoadGraphActionPerformed

    private void NewSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSimulationActionPerformed
    SimulateDates simulateDates = new SimulateDates();
    simulateDates.setVisible(true);
    this.setVisible(false);
    Simulation simulateWindouw = new Simulation();
    simulateWindouw // Implementar JFrame Simulation
    }//GEN-LAST:event_NewSimulationActionPerformed

    private void ShowGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowGraphActionPerformed
    Show showWindow = new Show();
    showWindow.setVisible(true);
    this.setVisible(false);
    showWindow  //Implementar interfaz
    }//GEN-LAST:event_ShowGraphActionPerformed

    private void SaveGraphInTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveGraphInTXTActionPerformed
       
    }//GEN-LAST:event_SaveGraphInTXTActionPerformed

    private void CloseProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseProgramActionPerformed
    System.exit(0); 
    }//GEN-LAST:event_CloseProgramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Modify and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseProgram;
    private javax.swing.JButton LoadGraph;
    private javax.swing.JButton ModifyGraph;
    private javax.swing.JButton NewSimulation;
    private javax.swing.JButton SaveGraphInTXT;
    private javax.swing.JButton ShowGraph;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
