/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package _06_Interfaces;

import _02_EDD.LinkedSimpleList;
import _02_EDD.UndirectedGraph;
import _02_EDD.Vertex;
import _03_Classes.Ant;
import _03_Classes.AntSystemCycle;
import _04_Functions.Function01Simulation;
import _04_Functions.Function06ViewWithGraphStream;
import javax.swing.JOptionPane;

/**
 *
 * @author AresR
 */
public class Simulation extends javax.swing.JFrame {

    public static UndirectedGraph GraphOfSimulation = new UndirectedGraph();
    public static int NumberOfCyclesToCompleteSimulation = 0;
    public static int antNumberToSimulation = 0;
    public static int alfaValueToSimulation = 0;
    public static int betaValueToSimulation = 0;
    public static double rhoValueToSimulation = 0;
    public static Vertex StartVertexToSimulation = new Vertex(0);
    public static Vertex EndVertexToSimulation = new Vertex(0);

    public static LinkedSimpleList listOfAntsToSimulation = new LinkedSimpleList();
    public static int CurrentCycleToSimulation = 0;
    public static boolean Prepared = false;
    public static AntSystemCycle currentSimulation = new AntSystemCycle();

    /**
     * Creates new form Simulation
     */
    public Simulation() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RefreshAndPrepareSimulation = new javax.swing.JButton();
        titleCurrentCycle = new javax.swing.JLabel();
        currentCycle = new javax.swing.JTextField();
        titleAntsNumber = new javax.swing.JLabel();
        AntsNumber = new javax.swing.JTextField();
        StartCicle = new javax.swing.JButton();
        GoToMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaToSummaryPerCycle = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RefreshAndPrepareSimulation.setText("Actualizar e iniciar simulacion");
        RefreshAndPrepareSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshAndPrepareSimulationActionPerformed(evt);
            }
        });

        titleCurrentCycle.setText("Numero del ciclo actual:");

        currentCycle.setText("0");

        titleAntsNumber.setText("Numero de hormigas:");

        AntsNumber.setText("0");

        StartCicle.setText("Iniciar ciclo");
        StartCicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartCicleActionPerformed(evt);
            }
        });

        GoToMenu.setText("Volver al menu");
        GoToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToMenuActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_07_Images/HormigaSiluetaNegra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(titleCurrentCycle)
                        .addGap(18, 18, 18)
                        .addComponent(currentCycle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(titleAntsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AntsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(StartCicle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GoToMenu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RefreshAndPrepareSimulation, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleCurrentCycle)
                    .addComponent(currentCycle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleAntsNumber)
                    .addComponent(AntsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartCicle))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RefreshAndPrepareSimulation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GoToMenu)
                        .addGap(47, 47, 47))))
        );

        textAreaToSummaryPerCycle.setColumns(20);
        textAreaToSummaryPerCycle.setRows(5);
        jScrollPane1.setViewportView(textAreaToSummaryPerCycle);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Simulación del algoritmo de optimización basado <br>  en el comportamiento de colonias de hormigas.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToMenuActionPerformed
        Prepared = false;
        CurrentCycleToSimulation = 0;
        Menu menuWindow = new Menu();
        menuWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GoToMenuActionPerformed

    private void StartCicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartCicleActionPerformed

        if (Prepared) {
            if (CurrentCycleToSimulation < NumberOfCyclesToCompleteSimulation) {
                Function01Simulation temporalFunction = new Function01Simulation();
                CurrentCycleToSimulation++;
                this.currentCycle.setText(String.valueOf(CurrentCycleToSimulation));

                this.textAreaToSummaryPerCycle.append("\n");
                for (int i = 0; i < currentSimulation.getListOfAnts().GetSize(); i++) {
                    Ant antN = (Ant) currentSimulation.getListOfAnts().GetValInIndex(i).GetData();
                    antN.getVertexsTraveled().insertLast(StartVertexToSimulation);
                }
                this.textAreaToSummaryPerCycle.append(currentSimulation.eachCycle(currentSimulation.getListOfAnts(), CurrentCycleToSimulation));
                currentSimulation.restartAnts();

                this.textAreaToSummaryPerCycle.append("\n");
                this.textAreaToSummaryPerCycle.append("Distancia mas corta: ");
                this.textAreaToSummaryPerCycle.append(String.valueOf(currentSimulation.getBestDistance()));
                this.textAreaToSummaryPerCycle.append(". Camino mas corto: ");
                this.textAreaToSummaryPerCycle.append(temporalFunction.FormatTxtToBestRouteArcs(currentSimulation.getBestRouteArcs()));
                this.textAreaToSummaryPerCycle.append("\n");

            } else {
                JOptionPane.showMessageDialog(null, "Simulacion finalizada.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Actualice e inicie la simulacion primero.");
        }
    }//GEN-LAST:event_StartCicleActionPerformed

    private void RefreshAndPrepareSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshAndPrepareSimulationActionPerformed
        if (!Prepared) {
            Function01Simulation temporalFunction = new Function01Simulation();

            LinkedSimpleList listOfAnts = temporalFunction.makeListOfAnts(Simulation.antNumberToSimulation, StartVertexToSimulation);
            listOfAntsToSimulation = listOfAnts;
            
            AntSystemCycle simulation = new AntSystemCycle(GraphOfSimulation, listOfAntsToSimulation, alfaValueToSimulation, betaValueToSimulation, rhoValueToSimulation, CurrentCycleToSimulation, StartVertexToSimulation, EndVertexToSimulation);
            currentSimulation = simulation;
            currentSimulation = temporalFunction.inicializePheromones(currentSimulation);

            String numOfAntsToshow = String.valueOf(antNumberToSimulation);
            this.AntsNumber.setText(numOfAntsToshow);

            Prepared = true;

            Function06ViewWithGraphStream temporal = new Function06ViewWithGraphStream();
            temporal.visualizeGraphWindouw(currentSimulation.getGraphOfSimulation());

        } else {
            JOptionPane.showMessageDialog(null, "Ya se inició una simulacion. Regrese al menu principal para iniciar otra.");
        }
    }//GEN-LAST:event_RefreshAndPrepareSimulationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AntsNumber;
    private javax.swing.JButton GoToMenu;
    private javax.swing.JButton RefreshAndPrepareSimulation;
    private javax.swing.JButton StartCicle;
    private javax.swing.JTextField currentCycle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaToSummaryPerCycle;
    private javax.swing.JLabel titleAntsNumber;
    private javax.swing.JLabel titleCurrentCycle;
    // End of variables declaration//GEN-END:variables
}
